### ISSUE TITLE
Testing scenarios

### ISSUE THREAD

**Issue by jonsayer** [SFDO-Community/UnsubscribeLink#43]
During the sprint, Margie and Eileen said they could work on the testing scenarios. However, at end of Thursday, they had not made much progress. 
 
- Testing scenarios doc: https://docs.google.com/spreadsheets/d/1MB5X1DN7YURj3zSARoVhCvQiFDAGdFMTTu73YsdYlxQ/edit?gid=0#gid=0
- Also, create additional test scenarios for testing the Unsubscribe Link as needed.

**Comment by salgsstyrke** [comment]
We need to test that you can run the setup flow multiple times and it will save your answers from before.

**Comment by salgsstyrke** [comment]
These were handled well at the sprint.
